name: Gradle
 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Apply permissions
        run: chmod +0777 gradlew
      - name: Gradle Build
        run: ./gradlew build
